// Code generated by sqlc. DO NOT EDIT.
// source: key_values.sql

package db

import (
	"context"
	"database/sql"
)

const getByKey = `-- name: GetByKey :one
select v from key_values where k = $1
`

func (q *Queries) GetByKey(ctx context.Context, k string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getByKey, k)
	var v sql.NullString
	err := row.Scan(&v)
	return v, err
}

const putKey = `-- name: PutKey :exec
insert into key_values (k, v) values ($1, $2)
`

type PutKeyParams struct {
	K string
	V sql.NullString
}

func (q *Queries) PutKey(ctx context.Context, arg PutKeyParams) error {
	_, err := q.db.ExecContext(ctx, putKey, arg.K, arg.V)
	return err
}
